const destinations = [
  {
    id: "jeju",
    name: "제주도",
    image: "photo/제주도1.png",
    tags: ["자연", "바다", "힐링", "액티비티", "국내"],
    companions: ["커플", "친구", "가족", "혼자"],
    budgets: ["보통", "여유"],
    durations: ["1박 2일", "2박 3일 이상"],
    seasons: ["봄", "여름", "가을"],
    popularity: 98,
    costValue: 78,
    cost: "약 35만~70만원",
    schedule: "2박 3일 이상",
    spots: ["성산일출봉", "협재해변", "우도"],
    reason: "바다와 오름, 카페와 액티비티를 한 번에 즐길 수 있어 취향 폭이 넓은 여행지입니다.",
    intro: "제주도는 자연 풍경, 해안 드라이브, 감성 카페, 로컬 맛집을 모두 담을 수 있는 대표 여행지입니다.",
    course: "1일차 애월 해안도로와 카페 거리, 2일차 성산일출봉과 우도, 3일차 협재해변과 동문시장",
    food: "고기국수, 흑돼지, 해물라면, 오션뷰 카페",
    transport: "렌터카 이용이 가장 편하고, 주요 관광지는 버스 이동도 가능합니다.",
    location: "제주특별자치도 전역. 공항 기준 애월, 성산, 서귀포 방향으로 코스를 나누면 이동이 편합니다.",
    season: "봄과 가을이 가장 쾌적하며 여름에는 해수욕 중심 일정이 좋습니다.",
    tips: "인기 맛집과 렌터카는 성수기 전에 미리 예약하는 편이 좋습니다."
  },
  {
    id: "gangneung",
    name: "강릉",
    image: "photo/강릉1.png",
    tags: ["바다", "카페", "힐링", "맛집", "국내"],
    companions: ["커플", "친구", "혼자"],
    budgets: ["저예산", "보통"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["봄", "가을", "겨울"],
    popularity: 90,
    costValue: 88,
    cost: "약 12만~28만원",
    schedule: "1박 2일",
    spots: ["안목해변", "경포호", "초당순두부마을"],
    reason: "바다 산책, 카페, 맛집 동선이 짧아 짧은 일정에도 만족도가 높습니다.",
    intro: "강릉은 바다와 카페 문화가 강한 여행지로, 주말에 가볍게 떠나기 좋습니다.",
    course: "안목해변 카페 거리, 경포호 산책, 중앙시장 먹거리, 주문진 바다 코스",
    food: "초당순두부, 장칼국수, 커피, 해산물",
    transport: "KTX 강릉역 도착 후 택시나 버스로 주요 해변 이동이 쉽습니다.",
    location: "강원특별자치도 강릉시. 안목해변, 경포호, 주문진을 한 방향으로 묶으면 좋습니다.",
    season: "사계절 모두 좋지만 맑은 가을과 겨울 바다 여행이 특히 인기가 많습니다.",
    tips: "주말 안목해변은 붐비므로 오전에 이동하면 여유롭습니다."
  },
  {
    id: "busan",
    name: "부산",
    image: "photo/부산1.png",
    tags: ["도시", "바다", "맛집", "쇼핑", "국내"],
    companions: ["친구", "가족", "커플"],
    budgets: ["보통", "여유"],
    durations: ["1박 2일", "2박 3일 이상"],
    seasons: ["여름", "가을", "겨울"],
    popularity: 96,
    costValue: 86,
    cost: "약 20만~45만원",
    schedule: "1박 2일",
    spots: ["해운대", "광안리", "감천문화마을"],
    reason: "대중교통으로 바다, 야경, 쇼핑, 맛집을 모두 연결하기 쉬운 도시 여행지입니다.",
    intro: "부산은 바다를 품은 대도시라 활동적인 일정과 쉬는 일정을 균형 있게 짤 수 있습니다.",
    course: "해운대 산책, 센텀시티 쇼핑, 광안리 야경, 감천문화마을과 국제시장",
    food: "돼지국밥, 밀면, 어묵, 회, 씨앗호떡",
    transport: "지하철과 버스 노선이 잘 되어 있어 차 없이 여행하기 좋습니다.",
    location: "부산광역시 해운대구, 수영구, 중구 일대. 해변권과 원도심권으로 나눠 이동하면 효율적입니다.",
    season: "여름은 해수욕, 가을과 겨울은 야경과 맛집 중심 여행에 좋습니다.",
    tips: "해운대와 광안리 숙소 가격 차이가 커서 일정 동선에 맞춰 고르는 것이 좋습니다."
  },
  {
    id: "jeonju",
    name: "전주",
    image: "photo/전주1.png",
    tags: ["역사/문화", "맛집", "도시", "국내"],
    companions: ["친구", "가족", "커플", "혼자"],
    budgets: ["저예산", "보통"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["봄", "가을", "겨울"],
    popularity: 87,
    costValue: 90,
    cost: "약 8만~22만원",
    schedule: "당일치기 또는 1박 2일",
    spots: ["전주한옥마을", "경기전", "남부시장"],
    reason: "한옥마을과 먹거리 동선이 가까워 저예산 여행에도 알찬 코스를 만들 수 있습니다.",
    intro: "전주는 전통 분위기와 음식 여행을 함께 즐기기 좋은 국내 대표 문화 여행지입니다.",
    course: "전주한옥마을, 경기전, 객리단길 카페, 남부시장 야시장",
    food: "비빔밥, 콩나물국밥, 막걸리 골목, 길거리 간식",
    transport: "전주역 또는 고속버스터미널에서 버스와 택시로 이동할 수 있습니다.",
    location: "전북특별자치도 전주시 완산구 한옥마을 주변. 도보 이동으로 주요 명소를 둘러보기 좋습니다.",
    season: "봄과 가을 한옥마을 산책이 좋고, 겨울에도 먹거리 여행으로 적합합니다.",
    tips: "한복 대여와 유명 식당은 주말 오후 대기 시간이 길 수 있습니다."
  },
  {
    id: "yeosu",
    name: "여수",
    image: "photo/여수1.png",
    tags: ["바다", "야경", "힐링", "맛집", "국내"],
    companions: ["커플", "가족", "친구"],
    budgets: ["보통", "여유"],
    durations: ["1박 2일", "2박 3일 이상"],
    seasons: ["봄", "여름", "가을"],
    popularity: 89,
    costValue: 82,
    cost: "약 18만~40만원",
    schedule: "1박 2일",
    spots: ["오동도", "해상케이블카", "낭만포차거리"],
    reason: "밤바다와 야경이 강점이라 커플 여행이나 가족 휴식 여행에 잘 맞습니다.",
    intro: "여수는 잔잔한 바다 풍경과 밤바다 감성을 중심으로 여유롭게 즐기기 좋은 여행지입니다.",
    course: "오동도 산책, 해상케이블카, 돌산공원 야경, 낭만포차거리",
    food: "게장백반, 갓김치, 해물삼합, 서대회",
    transport: "KTX 여수엑스포역에서 택시와 버스로 주요 명소 이동이 가능합니다.",
    location: "전라남도 여수시 해안권. 여수엑스포역, 오동도, 돌산공원을 연결하는 코스가 대표적입니다.",
    season: "봄, 가을에 산책하기 좋고 여름 밤바다 여행도 인기가 많습니다.",
    tips: "야경 명소는 해 질 무렵부터 붐비므로 일몰 시간을 확인하고 움직이면 좋습니다."
  },
  {
    id: "sokcho",
    name: "속초",
    image: "photo/속초1.png",
    tags: ["산", "바다", "자연", "맛집", "국내"],
    companions: ["친구", "가족", "커플"],
    budgets: ["저예산", "보통"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["가을", "겨울", "봄"],
    popularity: 85,
    costValue: 87,
    cost: "약 10만~30만원",
    schedule: "1박 2일",
    spots: ["설악산", "속초해변", "중앙시장"],
    reason: "산과 바다를 하루 안에 모두 볼 수 있어 자연 여행 만족도가 높습니다.",
    intro: "속초는 설악산과 동해 바다, 시장 먹거리를 함께 즐길 수 있는 균형 좋은 여행지입니다.",
    course: "설악산 케이블카, 속초해변, 영금정, 중앙시장 먹거리 투어",
    food: "닭강정, 오징어순대, 물회, 회국수",
    transport: "고속버스 이용 후 시내버스나 택시로 해변과 시장 이동이 편리합니다.",
    location: "강원특별자치도 속초시와 설악산 권역. 산 코스와 바다 코스를 반나절씩 나누기 좋습니다.",
    season: "가을 단풍철 설악산과 겨울 동해 바다가 특히 인상적입니다.",
    tips: "설악산 단풍철에는 교통 체증이 심해 이른 출발이 좋습니다."
  },
  {
    id: "yangyang",
    name: "양양",
    image: "photo/양양1.png",
    tags: ["바다", "액티비티", "힐링", "카페", "국내"],
    companions: ["친구", "커플", "혼자"],
    budgets: ["저예산", "보통"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["여름", "가을", "봄"],
    popularity: 81,
    costValue: 80,
    cost: "약 12만~30만원",
    schedule: "1박 2일",
    spots: ["서피비치", "낙산사", "하조대"],
    reason: "서핑과 바다 산책, 감성 카페를 짧은 일정에 담기 좋아 친구 여행에 잘 맞습니다.",
    intro: "양양은 동해 바다와 서핑 문화가 돋보이는 여행지로, 가볍게 떠나는 휴식 여행에 좋습니다.",
    course: "서피비치 산책과 서핑 체험, 낙산사 일몰, 하조대 해변과 카페 거리",
    food: "물회, 섭국, 막국수, 해변 카페",
    transport: "고속버스나 자가용 이용이 편하며, 해변 간 이동은 택시나 렌터카가 좋습니다.",
    location: "강원특별자치도 양양군 해안권. 낙산사, 하조대, 서피비치를 한 방향으로 묶기 좋습니다.",
    season: "여름에는 서핑과 해수욕, 가을에는 한적한 바다 산책이 좋습니다.",
    tips: "서핑 강습은 주말에 빨리 마감될 수 있어 미리 예약하는 편이 좋습니다."
  },
  {
    id: "gapyeong",
    name: "가평",
    image: "photo/가평1.png",
    tags: ["자연", "힐링", "액티비티", "카페", "국내"],
    companions: ["커플", "친구", "가족"],
    budgets: ["저예산", "보통"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["봄", "여름", "가을"],
    popularity: 82,
    costValue: 84,
    cost: "약 8만~25만원",
    schedule: "당일치기 또는 1박 2일",
    spots: ["남이섬", "아침고요수목원", "자라섬"],
    reason: "서울 근교에서 자연 산책과 액티비티를 함께 즐기기 좋아 부담 없이 다녀오기 좋습니다.",
    intro: "가평은 강과 숲, 수목원, 캠핑 감성을 가까운 거리에서 즐길 수 있는 근교 여행지입니다.",
    course: "남이섬 산책, 자라섬 피크닉, 아침고요수목원 야간 조명 또는 계절 정원",
    food: "잣두부, 닭갈비, 막국수, 브런치 카페",
    transport: "ITX 청춘과 버스를 이용하거나 자가용으로 주요 명소를 이동하기 좋습니다.",
    location: "경기도 가평군 일대. 남이섬, 자라섬, 아침고요수목원을 일정에 맞춰 나누면 좋습니다.",
    season: "봄꽃과 가을 단풍 시기가 특히 좋고, 여름에는 물놀이 일정도 인기가 많습니다.",
    tips: "주말에는 도로 정체가 잦아 오전 일찍 출발하면 일정이 편합니다."
  },
  {
    id: "seoul",
    name: "서울",
    image: "photo/서울1.png",
    tags: ["도시", "맛집", "쇼핑", "역사/문화", "국내"],
    companions: ["친구", "커플", "혼자", "가족"],
    budgets: ["저예산", "보통", "여유"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["봄", "가을", "겨울"],
    popularity: 94,
    costValue: 83,
    cost: "약 8만~35만원",
    schedule: "당일치기 또는 1박 2일",
    spots: ["경복궁", "코엑스", "남산타워"],
    reason: "전시, 쇼핑, 맛집, 고궁 산책까지 선택지가 많아 취향별 일정 구성이 쉽습니다.",
    intro: "서울은 전통과 최신 트렌드가 함께 있는 도시 여행지로, 짧은 일정에도 밀도 있게 즐길 수 있습니다.",
    course: "경복궁과 북촌 산책, 코엑스 쇼핑과 전시, 한강 또는 남산 야경",
    food: "광장시장 먹거리, 냉면, 디저트 카페, 한식 다이닝",
    transport: "지하철과 버스가 촘촘해 대중교통 중심 여행이 가장 편합니다.",
    location: "서울특별시 전역. 고궁권, 강남권, 성수와 한강권처럼 권역별로 묶으면 이동이 효율적입니다.",
    season: "봄 벚꽃과 가을 산책이 좋고, 겨울에는 전시와 실내 맛집 코스가 잘 맞습니다.",
    tips: "인기 전시와 식당은 사전 예약을 확인하면 대기 시간을 줄일 수 있습니다."
  },
  {
    id: "daejeon",
    name: "대전",
    image: "photo/대전1.png",
    tags: ["도시", "맛집", "자연", "힐링", "국내"],
    companions: ["친구", "가족", "혼자"],
    budgets: ["저예산", "보통"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["봄", "가을", "겨울"],
    popularity: 78,
    costValue: 89,
    cost: "약 7만~22만원",
    schedule: "당일치기 또는 1박 2일",
    spots: ["성심당", "한밭수목원", "엑스포과학공원"],
    reason: "교통 접근성이 좋고 빵집, 수목원, 과학공원 코스를 편하게 묶을 수 있습니다.",
    intro: "대전은 전국에서 접근하기 쉬운 도시로, 맛집과 가벼운 산책 일정을 함께 즐기기 좋습니다.",
    course: "성심당과 원도심 먹거리, 한밭수목원 산책, 엑스포과학공원과 대전신세계 주변",
    food: "튀김소보로, 칼국수, 두부두루치기, 로컬 카페",
    transport: "KTX 대전역과 지하철, 버스를 이용해 주요 지역을 이동할 수 있습니다.",
    location: "대전광역시 중구, 서구, 유성구 일대. 원도심과 둔산, 유성권을 나눠 보면 좋습니다.",
    season: "봄과 가을 수목원 산책이 좋고, 겨울에는 맛집 중심 실내 일정이 편합니다.",
    tips: "성심당 본점은 주말 대기가 길 수 있어 오전 방문이 비교적 좋습니다."
  },
  {
    id: "daegu",
    name: "대구",
    image: "photo/대구1.png",
    tags: ["도시", "맛집", "쇼핑", "역사/문화", "국내"],
    companions: ["친구", "커플", "혼자"],
    budgets: ["저예산", "보통"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["봄", "가을", "겨울"],
    popularity: 80,
    costValue: 88,
    cost: "약 8만~24만원",
    schedule: "1박 2일",
    spots: ["김광석거리", "서문시장", "동성로"],
    reason: "먹거리와 도심 산책, 시장 구경이 가까운 동선에 있어 짧은 여행으로도 알찹니다.",
    intro: "대구는 로컬 음식과 도심 문화, 시장 분위기를 함께 즐기기 좋은 도시 여행지입니다.",
    course: "김광석거리 산책, 동성로 카페와 쇼핑, 서문시장 야시장, 근대골목 투어",
    food: "막창, 납작만두, 따로국밥, 서문시장 간식",
    transport: "동대구역 도착 후 지하철과 버스로 도심권 이동이 편리합니다.",
    location: "대구광역시 중구와 동구 일대. 동성로, 서문시장, 김광석거리를 중심으로 묶기 좋습니다.",
    season: "봄과 가을 도보 여행이 좋고, 겨울에는 시장 먹거리 코스가 잘 맞습니다.",
    tips: "여름에는 더위가 강하므로 실내 카페와 쇼핑 일정을 함께 넣는 편이 좋습니다."
  },
  {
    id: "gwangju",
    name: "광주",
    image: "photo/광주1.png",
    tags: ["도시", "맛집", "역사/문화", "예술", "국내"],
    companions: ["친구", "가족", "혼자"],
    budgets: ["저예산", "보통"],
    durations: ["당일치기", "1박 2일"],
    seasons: ["봄", "가을", "겨울"],
    popularity: 79,
    costValue: 86,
    cost: "약 8만~25만원",
    schedule: "1박 2일",
    spots: ["양림동", "국립아시아문화전당", "무등산"],
    reason: "예술 산책과 남도 음식, 무등산 자연 코스를 취향에 맞게 조합하기 좋습니다.",
    intro: "광주는 문화 예술 공간과 깊은 맛의 음식 여행을 함께 즐길 수 있는 남도 도시 여행지입니다.",
    course: "양림동 역사문화마을, 국립아시아문화전당 전시, 무등산 산책, 송정역시장 먹거리",
    food: "떡갈비, 상추튀김, 오리탕, 한정식",
    transport: "광주송정역과 지하철, 버스를 이용해 도심과 주요 명소를 이동할 수 있습니다.",
    location: "광주광역시 동구, 남구, 광산구 일대. 문화전당과 양림동을 도보권으로 묶기 좋습니다.",
    season: "봄과 가을 도심 산책이 좋고, 겨울에는 전시와 음식 여행 중심 일정이 편합니다.",
    tips: "전시 일정과 시장 운영 시간을 미리 확인하면 동선 낭비를 줄일 수 있습니다."
  }
];

let favorites = [];
let booking = { trains: [], hotel: null };

const trainProducts = [
  { id: "ktx-morning", category: "train", type: "KTX", time: "08:20", duration: "약 2시간", price: 42000 },
  { id: "ktx-afternoon", category: "train", type: "KTX", time: "13:10", duration: "약 2시간 10분", price: 39800 },
  { id: "itx-evening", category: "train", type: "ITX", time: "18:40", duration: "약 2시간 35분", price: 28600 },
  { id: "flight-morning", category: "flight", type: "비행기", time: "09:30", duration: "약 1시간", price: 68000 },
  { id: "flight-afternoon", category: "flight", type: "비행기", time: "15:20", duration: "약 1시간 5분", price: 72000 },
  { id: "rental-compact", category: "car", type: "소형차 렌트", time: "종일", duration: "24시간 이용", price: 55000 },
  { id: "rental-suv", category: "car", type: "SUV 렌트", time: "종일", duration: "24시간 이용", price: 82000 }
];

const hotels = [
  {
    id: "gangneung-blue",
    destination: "강릉",
    name: "씨마크 호텔",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80",
    type: "오션뷰 호텔",
    rating: 4.7,
    price: 138000,
    description: "안목해변과 가까워 카페 거리와 바다 산책을 함께 즐기기 좋습니다.",
    services: ["오션뷰", "수영장", "스파", "조식 뷔페", "무료 주차"]
  },
  {
    id: "busan-harbor",
    destination: "부산",
    name: "파라다이스 호텔 부산",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=900&q=80",
    type: "도심 호텔",
    rating: 4.6,
    price: 126000,
    description: "광안리와 센텀 이동이 편해 친구 여행과 쇼핑 일정에 잘 맞습니다.",
    services: ["오션뷰", "온천 스파", "야외 수영장", "카지노", "무료 와이파이"]
  },
  {
    id: "jeju-garden",
    destination: "제주도",
    name: "롯데호텔 제주",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=900&q=80",
    type: "리조트",
    rating: 4.8,
    price: 182000,
    description: "정원과 수영장이 있어 가족, 커플 힐링 여행에 어울립니다.",
    services: ["인룸다이닝(룸서비스)", "유아/패밀리 케어", "시티/공항 셔틀", "레스토랑 및 부대시설", "온수풀, 스파, 피트니스 센터"]
  },
  {
    id: "yeosu-night",
    destination: "여수",
    name: "소노캄 여수",
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=900&q=80",
    type: "감성 펜션",
    rating: 4.5,
    price: 98000,
    description: "돌산대교 야경을 보기 좋고 낭만포차거리 이동도 편합니다.",
    services: ["오션뷰", "인피니티풀", "조식 제공", "카페", "피트니스센터"]
  },
  {
    id: "jeonju-hanok",
    destination: "전주",
    name: "라한호텔 전주",
    image: "photo/전주1.png",
    type: "한옥 숙소",
    rating: 4.7,
    price: 112000,
    description: "한옥마을 도보 여행에 편하고 전주 감성을 느끼기 좋은 숙소입니다.",
    services: ["무료 주차", "조식 제공", "한옥마을 근처", "와이파이 제공", "피트니스룸"]
  },
  {
    id: "sokcho-sea",
    destination: "속초",
    name: "롯데리조트 속초",
    image: "photo/속초1.png",
    type: "오션뷰 호텔",
    rating: 4.6,
    price: 132000,
    description: "속초해변과 중앙시장 이동이 편해 바다와 먹거리 일정을 함께 즐기기 좋습니다.",
    services: ["워터파크", "바다 전망", "가족 객실", "무료 주차", "키즈존"]
  },
  {
    id: "yangyang-surf",
    destination: "양양",
    name: "쏠비치 양양",
    image: "photo/양양1.png",
    type: "비치 게스트하우스",
    rating: 4.4,
    price: 89000,
    description: "서퍼비치와 가까워 액티비티 중심 여행에 잘 맞는 캐주얼한 숙소입니다.",
    services: ["해변 접근", "워터파크", "사우나", "조식 제공", "무료 주차"]
  },
  {
    id: "gapyeong-garden",
    destination: "가평",
    name: "마이다스 호텔&리조트",
    image: "photo/가평1.png",
    type: "숲속 펜션",
    rating: 4.5,
    price: 108000,
    description: "남이섬과 아침고요수목원 코스를 여유롭게 이어가기 좋은 숙소입니다.",
    services: ["북한강 전망", "가족 객실", "바비큐장", "카페", "무료 주차"]
  },
  {
    id: "seoul-city",
    destination: "서울",
    name: "롯데호텔 서울",
    image: "photo/서울1.png",
    type: "도심 호텔",
    rating: 4.7,
    price: 148000,
    description: "명동, 경복궁, 남산 이동이 쉬워 첫 서울 여행 일정에 편합니다.",
    services: ["실내 수영장", "피트니스센터", "발렛파킹", "룸서비스", "라운지 바"]
  },
  {
    id: "daejeon-station",
    destination: "대전",
    name: "호텔 오노마 대전",
    image: "photo/대전1.png",
    type: "비즈니스 호텔",
    rating: 4.3,
    price: 92000,
    description: "대전역과 성심당 접근성이 좋아 짧은 도시 여행에 실용적입니다.",
    services: ["신세계백화점 연결", "실내 수영장", "피트니스센터", "시티뷰", "무료 와이파이"]
  },
  {
    id: "daegu-downtown",
    destination: "대구",
    name: "대구 메리어트 호텔",
    image: "photo/대구1.png",
    type: "부티크 호텔",
    rating: 4.5,
    price: 104000,
    description: "동성로와 서문시장 이동이 편해 맛집과 쇼핑 일정을 잡기 좋습니다.",
    services: ["실내 수영장", "피트니스센터", "조식 뷔페", "무료 주차", "비즈니스룸"]
  },
  {
    id: "gwangju-art",
    destination: "광주",
    name: "홀리데이 인 광주 호텔",
    image: "photo/광주1.png",
    type: "레지던스",
    rating: 4.4,
    price: 97000,
    description: "아시아문화전당과 양림동을 둘러보기 좋은 차분한 숙소입니다.",
    services: ["실내 수영장", "스파", "피트니스센터", "조식 뷔페", "비즈니스센터"]
  }
];

